namespace ForaFinServices.Extensions
{
    using AutoMapper;
    using ForaFinServices.Constants;
    using ForaFinServices.DTO;
    using ForaFinServices.Models;
    using System;
    using System.Linq;

    public static class CompanyInfoExtensions
    {
        /// <summary>
        /// Maps to a <see cref="FundableAmountDto"/>
        /// </summary>
        /// <param name="owner"></param>
        /// <returns></returns>
        public static FundableAmountDto MapToFundableAmount(this CompanyInfo owner)
        {
            var standardFundableAmount = owner.CalculateStandardFundableAmount();
            var specialFundableAmount = owner.CalculateSpecialFundableAmount(standardFundableAmount);
            return new FundableAmountDto
            {
                Id = owner.Cik,
                Name = owner.EntityName,
                StandardFundableAmount = standardFundableAmount.WithPrecision(),
                SpecialFundableAmount = specialFundableAmount.WithPrecision()
            };
        }

        /// <summary>
        /// Returns the standard fundable amount based on it max recorded income between 2018 and 2022
        /// </summary>
        /// <requirements>
        /// Using highest income between 2018 and 2022:
        ///   If income is greater than or equal to $10B, standard fundable amount is 12.33% of income.
        ///   If income is less than $10B, standard fundable amount is 21.51% of income
        /// </requirements>
        private static decimal CalculateStandardFundableAmount(this CompanyInfo owner)
        {
            var standardFundableAmount = 0m;

            var units = owner.Facts?.UsGaap?.NetIncomeLoss?.Units;
            if (units == null)
                return standardFundableAmount;

            var usd10KOnly = units.GetUsd10KOnly();
            if (units!.HasStandardFundableAmounts() && usd10KOnly != null && usd10KOnly.Any())
            {
                var maxValue = usd10KOnly.Where(u => AppConstants.RequiredYears.Contains(u.GetYear())).Max(u => u.Val);
                return maxValue * (maxValue >= AppConstants.FundableThreshold
                    ? AppConstants.GreaterThan10BStandardFundableRatio
                    : AppConstants.LesserThan10BStandardFundableRatio);
            }
            return standardFundableAmount;
        }

        /// <summary>
        /// Returns the special fundable amount based on company name and income values between 2021 and 2022
        /// </summary>
        /// <requirements>
        /// Initially, the Special Fundable Amount is the same as Standard Fundable Amount.
        ///   If the company name starts with a vowel, add 15% to the standard funding amount.
        ///   If the company’s 2022 income was less than their 2021 income, subtract 25% from their standard funding amount.
        /// </requirements>
        private static decimal CalculateSpecialFundableAmount(this CompanyInfo owner, decimal standardFundableAmount)
        {
            var units = owner.Facts?.UsGaap?.NetIncomeLoss?.Units;
            if (units == null)
                return default;

            var usd10KOnly = units.GetUsd10KOnly();
            if (usd10KOnly == null || !usd10KOnly.Any())
                return default;

            if (units.HasStandardFundableAmounts() && usd10KOnly != null && usd10KOnly.Any())
            {
                var specialVowelAmount = owner.GetSpecialVowelAmount(standardFundableAmount);
                var specialIncomeDiffRule = owner.GetSpecialIncomeDiffRule(standardFundableAmount);
                return standardFundableAmount + specialVowelAmount - specialIncomeDiffRule;
            }
            return default;
        }

        private static decimal GetSpecialVowelAmount(this CompanyInfo owner, decimal amount)
        {
            // calculate special vowel rule
            return AppConstants.Vowels.ToList().Contains(owner.EntityName.ToLower().First()) 
                ? amount * AppConstants.SpecialVowelFundableRatio
                : 0;
        }

        private static decimal GetSpecialIncomeDiffRule(this CompanyInfo owner, decimal amount)
        {
            // special income diff between 2022 and 2021 rule
            var units = owner.Facts?.UsGaap?.NetIncomeLoss?.Units;
            var usd10KOnly = units!.GetUsd10KOnly();
            var specialUsds = usd10KOnly!.Where(u => AppConstants.IncomeYears.Contains(u.GetYear()));
            var usd2021 = specialUsds.First(u => u.GetYear() == AppConstants.Year2021);
            var usd2022 = specialUsds.First(u => u.GetYear() == AppConstants.Year2022);
            if (usd2022.Val < usd2021.Val)
            {
                return amount * AppConstants.SpecialIncomeDiffFundableRatio;
            }

            return default;
        }

        public static BaseFinancialResource? GetFinancialResource(this CompanyInfo owner, string resourceType) => resourceType switch
        {
            "entityCommonStockSharesOutstanding" => owner.Facts.Dei.EntityCommonStockSharesOutstanding,
            "entityNumberOfEmployees" => owner.Facts.Dei.EntityNumberOfEmployees,
            "entityPublicFloat" => owner.Facts.Dei.EntityPublicFloat,
            "accountsAndOtherReceivablesNetCurrent" => owner.Facts.UsGaap.AccountsAndOtherReceivablesNetCurrent,
            "accountsPayableCurrent" => owner.Facts.UsGaap.AccountsPayableCurrent,
            "accountsReceivableGross" => owner.Facts.UsGaap.AccountsReceivableGross,
            "accountsReceivableGrossCurrent" => owner.Facts.UsGaap.AccountsReceivableGrossCurrent,
            "accountsReceivableNet" => owner.Facts.UsGaap.AccountsReceivableNet,
            "accountsReceivableNetCurrent" => owner.Facts.UsGaap.AccountsReceivableNetCurrent,
            "accrualForTaxesOtherThanIncomeTaxesCurrent" => owner.Facts.UsGaap.AccrualForTaxesOtherThanIncomeTaxesCurrent,
            "accruedRentCurrent" => owner.Facts.UsGaap.AccruedRentCurrent,
            "accumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment" => owner.Facts.UsGaap.AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,
            "accumulatedOtherComprehensiveIncomeLossDefinedBenefitPensionAndOtherPostretirementPlansNetOfTax" => owner.Facts.UsGaap.AccumulatedOtherComprehensiveIncomeLossDefinedBenefitPensionAndOtherPostretirementPlansNetOfTax,
            "accumulatedOtherComprehensiveIncomeLossNetOfTax" => owner.Facts.UsGaap.AccumulatedOtherComprehensiveIncomeLossNetOfTax,
            "additionalPaidInCapital" => owner.Facts.UsGaap.AdditionalPaidInCapital,
            "adjustmentsRelatedToTaxWithholdingForShareBasedCompensation" => owner.Facts.UsGaap.AdjustmentsRelatedToTaxWithholdingForShareBasedCompensation,
            "adjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue" => owner.Facts.UsGaap.AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue,
            "adjustmentsToAdditionalPaidInCapitalTaxEffectFromShareBasedCompensation" => owner.Facts.UsGaap.AdjustmentsToAdditionalPaidInCapitalTaxEffectFromShareBasedCompensation,
            "advertisingExpense" => owner.Facts.UsGaap.AdvertisingExpense,
            "allocatedShareBasedCompensationExpense" => owner.Facts.UsGaap.AllocatedShareBasedCompensationExpense,
            "allowanceForDoubtfulAccountsReceivable" => owner.Facts.UsGaap.AllowanceForDoubtfulAccountsReceivable,
            "allowanceForDoubtfulAccountsReceivableCurrent" => owner.Facts.UsGaap.AllowanceForDoubtfulAccountsReceivableCurrent,
            "allowanceForDoubtfulAccountsReceivableWriteOffs" => owner.Facts.UsGaap.AllowanceForDoubtfulAccountsReceivableWriteOffs,
            "amortizationOfDebtDiscountPremium" => owner.Facts.UsGaap.AmortizationOfDebtDiscountPremium,
            "amortizationOfFinancingCostsAndDiscounts" => owner.Facts.UsGaap.AmortizationOfFinancingCostsAndDiscounts,
            "amortizationOfIntangibleAssets" => owner.Facts.UsGaap.AmortizationOfIntangibleAssets,
            "antidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount" => owner.Facts.UsGaap.AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount,
            "assetRetirementObligation" => owner.Facts.UsGaap.AssetRetirementObligation,
            "assetRetirementObligationAccretionExpense" => owner.Facts.UsGaap.AssetRetirementObligationAccretionExpense,
            "assetRetirementObligationLiabilitiesIncurred" => owner.Facts.UsGaap.AssetRetirementObligationLiabilitiesIncurred,
            "assetRetirementObligationLiabilitiesSettled" => owner.Facts.UsGaap.AssetRetirementObligationLiabilitiesSettled,
            "assetRetirementObligationRevisionOfEstimate" => owner.Facts.UsGaap.AssetRetirementObligationRevisionOfEstimate,
            "assets" => owner.Facts.UsGaap.Assets,
            "assetsCurrent" => owner.Facts.UsGaap.AssetsCurrent,
            "assetsHeldForSaleCurrent" => owner.Facts.UsGaap.AssetsHeldForSaleCurrent,
            "assetsHeldForSaleNotPartOfDisposalGroup" => owner.Facts.UsGaap.AssetsHeldForSaleNotPartOfDisposalGroup,
            "assetsHeldForSaleNotPartOfDisposalGroupCurrent" => owner.Facts.UsGaap.AssetsHeldForSaleNotPartOfDisposalGroupCurrent,
            "assetsNoncurrent" => owner.Facts.UsGaap.AssetsNoncurrent,
            "assetsOfDisposalGroupIncludingDiscontinuedOperationCurrent" => owner.Facts.UsGaap.AssetsOfDisposalGroupIncludingDiscontinuedOperationCurrent,
            "bankOverdrafts" => owner.Facts.UsGaap.BankOverdrafts,
            "bridgeLoan" => owner.Facts.UsGaap.BridgeLoan,
            "businessAcquisitionCostOfAcquiredEntityTransactionCosts" => owner.Facts.UsGaap.BusinessAcquisitionCostOfAcquiredEntityTransactionCosts,
            "businessAcquisitionEquityInterestIssuedOrIssuableValueAssigned" => owner.Facts.UsGaap.BusinessAcquisitionEquityInterestIssuedOrIssuableValueAssigned,
            "businessAcquisitionPreacquisitionContingencyAmount" => owner.Facts.UsGaap.BusinessAcquisitionPreacquisitionContingencyAmount,
            "businessAcquisitionProFormaEarningsPerShareBasic" => owner.Facts.UsGaap.BusinessAcquisitionProFormaEarningsPerShareBasic,
            "businessAcquisitionProFormaEarningsPerShareDiluted" => owner.Facts.UsGaap.BusinessAcquisitionProFormaEarningsPerShareDiluted,
            "businessAcquisitionProFormaIncomeLossFromContinuingOperationsBeforeChangesInAccountingAndExtraordinaryItemsNetOfTax" => owner.Facts.UsGaap.BusinessAcquisitionProFormaIncomeLossFromContinuingOperationsBeforeChangesInAccountingAndExtraordinaryItemsNetOfTax,
            "businessAcquisitionProFormaNetIncomeLoss" => owner.Facts.UsGaap.BusinessAcquisitionProFormaNetIncomeLoss,
            "businessAcquisitionProFormaRevenue" => owner.Facts.UsGaap.BusinessAcquisitionProFormaRevenue,
            "businessAcquisitionPurchasePriceAllocationAssetsAcquiredLiabilitiesAssumedNet" => owner.Facts.UsGaap.BusinessAcquisitionPurchasePriceAllocationAssetsAcquiredLiabilitiesAssumedNet,
            "businessAcquisitionPurchasePriceAllocationGoodwillAmount" => owner.Facts.UsGaap.BusinessAcquisitionPurchasePriceAllocationGoodwillAmount,
            "businessAcquisitionPurchasePriceAllocationPropertyPlantAndEquipment" => owner.Facts.UsGaap.BusinessAcquisitionPurchasePriceAllocationPropertyPlantAndEquipment,
            "businessAcquisitionsProFormaNetIncomeLoss" => owner.Facts.UsGaap.BusinessAcquisitionsProFormaNetIncomeLoss,
            "businessAcquisitionsProFormaRevenue" => owner.Facts.UsGaap.BusinessAcquisitionsProFormaRevenue,
            "businessCombinationAcquiredReceivablesEstimatedUncollectible" => owner.Facts.UsGaap.BusinessCombinationAcquiredReceivablesEstimatedUncollectible,
            "businessCombinationAcquiredReceivablesFairValue" => owner.Facts.UsGaap.BusinessCombinationAcquiredReceivablesFairValue,
            "businessCombinationAcquiredReceivablesGrossContractualAmount" => owner.Facts.UsGaap.BusinessCombinationAcquiredReceivablesGrossContractualAmount,
            "businessCombinationAcquisitionRelatedCosts" => owner.Facts.UsGaap.BusinessCombinationAcquisitionRelatedCosts,
            "businessCombinationProFormaInformationRevenueOfAcquireeSinceAcquisitionDateActual" => owner.Facts.UsGaap.BusinessCombinationProFormaInformationRevenueOfAcquireeSinceAcquisitionDateActual,
            "capitalExpendituresIncurredButNotYetPaid" => owner.Facts.UsGaap.CapitalExpendituresIncurredButNotYetPaid,
            "capitalizedContractCostNet" => owner.Facts.UsGaap.CapitalizedContractCostNet,
            "capitalizedContractCostNetCurrent" => owner.Facts.UsGaap.CapitalizedContractCostNetCurrent,
            "capitalLeasedAssetsGross" => owner.Facts.UsGaap.CapitalLeasedAssetsGross,
            "capitalLeaseObligations" => owner.Facts.UsGaap.CapitalLeaseObligations,
            "capitalLeaseObligationsCurrent" => owner.Facts.UsGaap.CapitalLeaseObligationsCurrent,
            "capitalLeaseObligationsNoncurrent" => owner.Facts.UsGaap.CapitalLeaseObligationsNoncurrent,
            "capitalLeasesFutureMinimumPaymentsDue" => owner.Facts.UsGaap.CapitalLeasesFutureMinimumPaymentsDue,
            "capitalLeasesFutureMinimumPaymentsDueCurrent" => owner.Facts.UsGaap.CapitalLeasesFutureMinimumPaymentsDueCurrent,
            "capitalLeasesFutureMinimumPaymentsDueInFiveYears" => owner.Facts.UsGaap.CapitalLeasesFutureMinimumPaymentsDueInFiveYears,
            "capitalLeasesFutureMinimumPaymentsDueInFourYears" => owner.Facts.UsGaap.CapitalLeasesFutureMinimumPaymentsDueInFourYears,
            "capitalLeasesFutureMinimumPaymentsDueInThreeYears" => owner.Facts.UsGaap.CapitalLeasesFutureMinimumPaymentsDueInThreeYears,
            "capitalLeasesFutureMinimumPaymentsDueInTwoYears" => owner.Facts.UsGaap.CapitalLeasesFutureMinimumPaymentsDueInTwoYears,
            "capitalLeasesFutureMinimumPaymentsDueThereafter" => owner.Facts.UsGaap.CapitalLeasesFutureMinimumPaymentsDueThereafter,
            "capitalLeasesFutureMinimumPaymentsPresentValueOfNetMinimumPayments" => owner.Facts.UsGaap.CapitalLeasesFutureMinimumPaymentsPresentValueOfNetMinimumPayments,
            "capitalLeasesIncomeStatementAmortizationExpense" => owner.Facts.UsGaap.CapitalLeasesIncomeStatementAmortizationExpense,
            "capitalLeasesLesseeBalanceSheetAssetsByMajorClassAccumulatedDeprecation" => owner.Facts.UsGaap.CapitalLeasesLesseeBalanceSheetAssetsByMajorClassAccumulatedDeprecation,
            "cashAcquiredFromAcquisition" => owner.Facts.UsGaap.CashAcquiredFromAcquisition,
            "cashAndCashEquivalentsAtCarryingValue" => owner.Facts.UsGaap.CashAndCashEquivalentsAtCarryingValue,
            "cashAndCashEquivalentsPeriodIncreaseDecrease" => owner.Facts.UsGaap.CashAndCashEquivalentsPeriodIncreaseDecrease,
            "cashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents" => owner.Facts.UsGaap.CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents,
            "cashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations" => owner.Facts.UsGaap.CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations,
            "cashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect" => owner.Facts.UsGaap.CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect,
            "cashPaidForCapitalizedInterest" => owner.Facts.UsGaap.CashPaidForCapitalizedInterest,
            "cashSurrenderValueOfLifeInsurance" => owner.Facts.UsGaap.CashSurrenderValueOfLifeInsurance,
            "commonStockCapitalSharesReservedForFutureIssuance" => owner.Facts.UsGaap.CommonStockCapitalSharesReservedForFutureIssuance,
            "commonStockDividendsPerShareCashPaid" => owner.Facts.UsGaap.CommonStockDividendsPerShareCashPaid,
            "commonStockDividendsPerShareDeclared" => owner.Facts.UsGaap.CommonStockDividendsPerShareDeclared,
            "commonStockParOrStatedValuePerShare" => owner.Facts.UsGaap.CommonStockParOrStatedValuePerShare,
            "commonStockSharesAuthorized" => owner.Facts.UsGaap.CommonStockSharesAuthorized,
            "commonStockSharesIssued" => owner.Facts.UsGaap.CommonStockSharesIssued,
            "commonStockSharesOutstanding" => owner.Facts.UsGaap.CommonStockSharesOutstanding,
            "commonStockValue" => owner.Facts.UsGaap.CommonStockValue,
            "comprehensiveIncomeNetOfTax" => owner.Facts.UsGaap.ComprehensiveIncomeNetOfTax,
            "comprehensiveIncomeNetOfTaxAttributableToNoncontrollingInterest" => owner.Facts.UsGaap.ComprehensiveIncomeNetOfTaxAttributableToNoncontrollingInterest,
            "comprehensiveIncomeNetOfTaxIncludingPortionAttributableToNoncontrollingInterest" => owner.Facts.UsGaap.ComprehensiveIncomeNetOfTaxIncludingPortionAttributableToNoncontrollingInterest,
            "constructionInProgressGross" => owner.Facts.UsGaap.ConstructionInProgressGross,
            "contractWithCustomerAssetNet" => owner.Facts.UsGaap.ContractWithCustomerAssetNet,
            "contractWithCustomerAssetNetCurrent" => owner.Facts.UsGaap.ContractWithCustomerAssetNetCurrent,
            "contractWithCustomerLiability" => owner.Facts.UsGaap.ContractWithCustomerLiability,
            "contractWithCustomerLiabilityCurrent" => owner.Facts.UsGaap.ContractWithCustomerLiabilityCurrent,
            "contractWithCustomerLiabilityNoncurrent" => owner.Facts.UsGaap.ContractWithCustomerLiabilityNoncurrent,
            "contractWithCustomerLiabilityRevenueRecognized" => owner.Facts.UsGaap.ContractWithCustomerLiabilityRevenueRecognized,
            "contractWithCustomerPerformanceObligationSatisfiedInPreviousPeriod" => owner.Facts.UsGaap.ContractWithCustomerPerformanceObligationSatisfiedInPreviousPeriod,
            "contractWithCustomerReceivableAllowanceForCreditLoss" => owner.Facts.UsGaap.ContractWithCustomerReceivableAllowanceForCreditLoss,
            "costOfGoodsAndServicesSold" => owner.Facts.UsGaap.CostOfGoodsAndServicesSold,
            "costsAndExpenses" => owner.Facts.UsGaap.CostsAndExpenses,
            "cumulativeEffectOfNewAccountingPrincipleInPeriodOfAdoption" => owner.Facts.UsGaap.CumulativeEffectOfNewAccountingPrincipleInPeriodOfAdoption,
            "currentFederalTaxExpenseBenefit" => owner.Facts.UsGaap.CurrentFederalTaxExpenseBenefit,
            "currentForeignTaxExpenseBenefit" => owner.Facts.UsGaap.CurrentForeignTaxExpenseBenefit,
            "currentStateAndLocalTaxExpenseBenefit" => owner.Facts.UsGaap.CurrentStateAndLocalTaxExpenseBenefit,
            "customerAdvancesAndDepositsCurrent" => owner.Facts.UsGaap.CustomerAdvancesAndDepositsCurrent,
            "debtAndCapitalLeaseObligations" => owner.Facts.UsGaap.DebtAndCapitalLeaseObligations,
            "debtInstrumentCarryingAmount" => owner.Facts.UsGaap.DebtInstrumentCarryingAmount,
            "debtInstrumentUnamortizedDiscountPremiumNet" => owner.Facts.UsGaap.DebtInstrumentUnamortizedDiscountPremiumNet,
            "deferredCostsCurrent" => owner.Facts.UsGaap.DeferredCostsCurrent,
            "deferredCreditsAndOtherLiabilitiesNoncurrent" => owner.Facts.UsGaap.DeferredCreditsAndOtherLiabilitiesNoncurrent,
            "deferredFederalIncomeTaxExpenseBenefit" => owner.Facts.UsGaap.DeferredFederalIncomeTaxExpenseBenefit,
            "deferredFinanceCostsNet" => owner.Facts.UsGaap.DeferredFinanceCostsNet,
            "deferredForeignIncomeTaxExpenseBenefit" => owner.Facts.UsGaap.DeferredForeignIncomeTaxExpenseBenefit,
            "deferredIncomeTaxAssetsNet" => owner.Facts.UsGaap.DeferredIncomeTaxAssetsNet,
            "deferredIncomeTaxExpenseBenefit" => owner.Facts.UsGaap.DeferredIncomeTaxExpenseBenefit,
            "deferredIncomeTaxLiabilities" => owner.Facts.UsGaap.DeferredIncomeTaxLiabilities,
            "deferredIncomeTaxLiabilitiesNet" => owner.Facts.UsGaap.DeferredIncomeTaxLiabilitiesNet,
            "deferredRevenueAndCreditsCurrent" => owner.Facts.UsGaap.DeferredRevenueAndCreditsCurrent,
            "deferredRevenueAndCreditsNoncurrent" => owner.Facts.UsGaap.DeferredRevenueAndCreditsNoncurrent,
            "deferredRevenueNoncurrent" => owner.Facts.UsGaap.DeferredRevenueNoncurrent,
            "deferredSalesCommission" => owner.Facts.UsGaap.DeferredSalesCommission,
            "deferredStateAndLocalIncomeTaxExpenseBenefit" => owner.Facts.UsGaap.DeferredStateAndLocalIncomeTaxExpenseBenefit,
            "deferredTaxAssetsGross" => owner.Facts.UsGaap.DeferredTaxAssetsGross,
            "deferredTaxAssetsLiabilitiesNet" => owner.Facts.UsGaap.DeferredTaxAssetsLiabilitiesNet,
            "deferredTaxAssetsLiabilitiesNetCurrent" => owner.Facts.UsGaap.DeferredTaxAssetsLiabilitiesNetCurrent,
            "deferredTaxAssetsLiabilitiesNetNoncurrent" => owner.Facts.UsGaap.DeferredTaxAssetsLiabilitiesNetNoncurrent,
            "deferredTaxAssetsNet" => owner.Facts.UsGaap.DeferredTaxAssetsNet,
            "deferredTaxAssetsNetCurrent" => owner.Facts.UsGaap.DeferredTaxAssetsNetCurrent,
            "deferredTaxAssetsNetNoncurrent" => owner.Facts.UsGaap.DeferredTaxAssetsNetNoncurrent,
            "deferredTaxAssetsOperatingLossCarryforwards" => owner.Facts.UsGaap.DeferredTaxAssetsOperatingLossCarryforwards,
            "deferredTaxAssetsOperatingLossCarryforwardsStateAndLocal" => owner.Facts.UsGaap.DeferredTaxAssetsOperatingLossCarryforwardsStateAndLocal,
            "deferredTaxAssetsOther" => owner.Facts.UsGaap.DeferredTaxAssetsOther,
            "deferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsEmployeeBenefits" => owner.Facts.UsGaap.DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsEmployeeBenefits,
            "deferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsOther" => owner.Facts.UsGaap.DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsOther,
            "deferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsPostretirementBenefits" => owner.Facts.UsGaap.DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsPostretirementBenefits,
            "deferredTaxAssetsValuationAllowance" => owner.Facts.UsGaap.DeferredTaxAssetsValuationAllowance,
            "deferredTaxLiabilities" => owner.Facts.UsGaap.DeferredTaxLiabilities,
            "deferredTaxLiabilitiesGoodwillAndIntangibleAssets" => owner.Facts.UsGaap.DeferredTaxLiabilitiesGoodwillAndIntangibleAssets,
            "deferredTaxLiabilitiesGrossNoncurrent" => owner.Facts.UsGaap.DeferredTaxLiabilitiesGrossNoncurrent,
            "deferredTaxLiabilitiesNoncurrent" => owner.Facts.UsGaap.DeferredTaxLiabilitiesNoncurrent,
            "deferredTaxLiabilitiesOther" => owner.Facts.UsGaap.DeferredTaxLiabilitiesOther,
            "deferredTaxLiabilitiesPropertyPlantAndEquipment" => owner.Facts.UsGaap.DeferredTaxLiabilitiesPropertyPlantAndEquipment,
            "definedBenefitPensionPlanLiabilitiesNoncurrent" => owner.Facts.UsGaap.DefinedBenefitPensionPlanLiabilitiesNoncurrent,
            "definedBenefitPlanAccumulatedBenefitObligation" => owner.Facts.UsGaap.DefinedBenefitPlanAccumulatedBenefitObligation,
            "definedBenefitPlanActualReturnOnPlanAssets" => owner.Facts.UsGaap.DefinedBenefitPlanActualReturnOnPlanAssets,
            "definedBenefitPlanAssumptionsUsedCalculatingBenefitObligationRateOfCompensationIncrease" => owner.Facts.UsGaap.DefinedBenefitPlanAssumptionsUsedCalculatingBenefitObligationRateOfCompensationIncrease,
            "definedBenefitPlanAssumptionsUsedCalculatingNetPeriodicBenefitCostRateOfCompensationIncrease" => owner.Facts.UsGaap.DefinedBenefitPlanAssumptionsUsedCalculatingNetPeriodicBenefitCostRateOfCompensationIncrease,
            "definedBenefitPlanBenefitObligation" => owner.Facts.UsGaap.DefinedBenefitPlanBenefitObligation,
            "definedBenefitPlanCostOfProvidingSpecialOrContractualTerminationBenefitRecognizedDuringPeriod" => owner.Facts.UsGaap.DefinedBenefitPlanCostOfProvidingSpecialOrContractualTerminationBenefitRecognizedDuringPeriod,
            "definedBenefitPlanEffectOfOnePercentagePointDecreaseOnAccumulatedPostretirementBenefitObligation1" => owner.Facts.UsGaap.DefinedBenefitPlanEffectOfOnePercentagePointDecreaseOnAccumulatedPostretirementBenefitObligation1,
            "definedBenefitPlanEffectOfOnePercentagePointDecreaseOnServiceAndInterestCostComponents1" => owner.Facts.UsGaap.DefinedBenefitPlanEffectOfOnePercentagePointDecreaseOnServiceAndInterestCostComponents1,
            "definedBenefitPlanEffectOfOnePercentagePointIncreaseOnAccumulatedPostretirementBenefitObligation" => owner.Facts.UsGaap.DefinedBenefitPlanEffectOfOnePercentagePointIncreaseOnAccumulatedPostretirementBenefitObligation,
            "definedBenefitPlanEffectOfOnePercentagePointIncreaseOnServiceAndInterestCostComponents" => owner.Facts.UsGaap.DefinedBenefitPlanEffectOfOnePercentagePointIncreaseOnServiceAndInterestCostComponents,
            "definedBenefitPlanExpectedFutureBenefitPaymentsNextTwelveMonths" => owner.Facts.UsGaap.DefinedBenefitPlanExpectedFutureBenefitPaymentsNextTwelveMonths,
            "definedBenefitPlanExpectedReturnOnPlanAssets" => owner.Facts.UsGaap.DefinedBenefitPlanExpectedReturnOnPlanAssets,
            "definedBenefitPlanOtherCosts" => owner.Facts.UsGaap.DefinedBenefitPlanOtherCosts,
            "definedBenefitPlanRecognizedNetGainLossDueToSettlements1" => owner.Facts.UsGaap.DefinedBenefitPlanRecognizedNetGainLossDueToSettlements1,
            "definedBenefitPlanSettlementsBenefitObligation" => owner.Facts.UsGaap.DefinedBenefitPlanSettlementsBenefitObligation,
            "definedBenefitPlanSettlementsPlanAssets" => owner.Facts.UsGaap.DefinedBenefitPlanSettlementsPlanAssets,
            "definedBenefitPlanUltimateHealthCareCostTrendRate" => owner.Facts.UsGaap.DefinedBenefitPlanUltimateHealthCareCostTrendRate,
            "definedBenefitPlanUltimateHealthCareCostTrendRate1" => owner.Facts.UsGaap.DefinedBenefitPlanUltimateHealthCareCostTrendRate1,
            "definedContributionPlanCostRecognized" => owner.Facts.UsGaap.DefinedContributionPlanCostRecognized,
            "depreciation" => owner.Facts.UsGaap.Depreciation,
            "depreciationAndAmortization" => owner.Facts.UsGaap.DepreciationAndAmortization,
            "depreciationDepletionAndAmortization" => owner.Facts.UsGaap.DepreciationDepletionAndAmortization,
            "disposalGroupIncludingDiscontinuedOperationCashAndCashEquivalents" => owner.Facts.UsGaap.DisposalGroupIncludingDiscontinuedOperationCashAndCashEquivalents,
            "disposalGroupIncludingDiscontinuedOperationIntangibleAssetsCurrent" => owner.Facts.UsGaap.DisposalGroupIncludingDiscontinuedOperationIntangibleAssetsCurrent,
            "disposalGroupIncludingDiscontinuedOperationLongLivedAssetsCurrent" => owner.Facts.UsGaap.DisposalGroupIncludingDiscontinuedOperationLongLivedAssetsCurrent,
            "disposalGroupNotDiscontinuedOperationGainLossOnDisposal" => owner.Facts.UsGaap.DisposalGroupNotDiscontinuedOperationGainLossOnDisposal,
            "dividendsCommonStock" => owner.Facts.UsGaap.DividendsCommonStock,
            "dividendsCommonStockCash" => owner.Facts.UsGaap.DividendsCommonStockCash,
            "dividendsPayableCurrent" => owner.Facts.UsGaap.DividendsPayableCurrent,
            "dividendsPreferredStockCash" => owner.Facts.UsGaap.DividendsPreferredStockCash,
            "dueFromAffiliateCurrent" => owner.Facts.UsGaap.DueFromAffiliateCurrent,
            "earningsPerShareBasic" => owner.Facts.UsGaap.EarningsPerShareBasic,
            "earningsPerShareBasicAndDiluted" => owner.Facts.UsGaap.EarningsPerShareBasicAndDiluted,
            "earningsPerShareDiluted" => owner.Facts.UsGaap.EarningsPerShareDiluted,
            "effectiveIncomeTaxRateContinuingOperations" => owner.Facts.UsGaap.EffectiveIncomeTaxRateContinuingOperations,
            "effectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate,
            "effectiveIncomeTaxRateReconciliationChangeInDeferredTaxAssetsValuationAllowance" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationChangeInDeferredTaxAssetsValuationAllowance,
            "effectiveIncomeTaxRateReconciliationChangeInEnactedTaxRate" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationChangeInEnactedTaxRate,
            "effectiveIncomeTaxRateReconciliationDeductionsDividends" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationDeductionsDividends,
            "effectiveIncomeTaxRateReconciliationDeductionsOther" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationDeductionsOther,
            "effectiveIncomeTaxRateReconciliationDispositionOfAssets" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationDispositionOfAssets,
            "effectiveIncomeTaxRateReconciliationForeignIncomeTaxRateDifferential" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationForeignIncomeTaxRateDifferential,
            "effectiveIncomeTaxRateReconciliationNondeductibleExpenseImpairmentLosses" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationNondeductibleExpenseImpairmentLosses,
            "effectiveIncomeTaxRateReconciliationNondeductibleExpenseLifeInsurance" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationNondeductibleExpenseLifeInsurance,
            "effectiveIncomeTaxRateReconciliationNondeductibleExpenseOther" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationNondeductibleExpenseOther,
            "effectiveIncomeTaxRateReconciliationOtherAdjustments" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationOtherAdjustments,
            "effectiveIncomeTaxRateReconciliationOtherReconcilingItemsPercent" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationOtherReconcilingItemsPercent,
            "effectiveIncomeTaxRateReconciliationStateAndLocalIncomeTaxes" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationStateAndLocalIncomeTaxes,
            "effectiveIncomeTaxRateReconciliationTaxContingencies" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationTaxContingencies,
            "effectiveIncomeTaxRateReconciliationTaxContingenciesStateAndLocal" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationTaxContingenciesStateAndLocal,
            "effectiveIncomeTaxRateReconciliationTaxCreditsResearch" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationTaxCreditsResearch,
            "effectOfExchangeRateOnCashAndCashEquivalents" => owner.Facts.UsGaap.EffectOfExchangeRateOnCashAndCashEquivalents,
            "effectOfExchangeRateOnCashAndCashEquivalentsContinuingOperations" => owner.Facts.UsGaap.EffectOfExchangeRateOnCashAndCashEquivalentsContinuingOperations,
            "employeeRelatedLiabilitiesCurrent" => owner.Facts.UsGaap.EmployeeRelatedLiabilitiesCurrent,
            "employeeServiceShareBasedCompensationCashReceivedFromExerciseOfStockOptions" => owner.Facts.UsGaap.EmployeeServiceShareBasedCompensationCashReceivedFromExerciseOfStockOptions,
            "employeeServiceShareBasedCompensationNonvestedAwardsTotalCompensationCostNotYetRecognized" => owner.Facts.UsGaap.EmployeeServiceShareBasedCompensationNonvestedAwardsTotalCompensationCostNotYetRecognized,
            "employeeServiceShareBasedCompensationNonvestedAwardsTotalCompensationCostNotYetRecognizedPeriodForRecognition" => owner.Facts.UsGaap.EmployeeServiceShareBasedCompensationNonvestedAwardsTotalCompensationCostNotYetRecognizedPeriodForRecognition,
            "employeeServiceShareBasedCompensationTaxBenefitFromCompensationExpense" => owner.Facts.UsGaap.EmployeeServiceShareBasedCompensationTaxBenefitFromCompensationExpense,
            "employeeServiceShareBasedCompensationTaxBenefitRealizedFromExerciseOfStockOptions" => owner.Facts.UsGaap.EmployeeServiceShareBasedCompensationTaxBenefitRealizedFromExerciseOfStockOptions,
            "employeeServiceShareBasedCompensationUnrecognizedCompensationCostsOnNonvestedAwards" => owner.Facts.UsGaap.EmployeeServiceShareBasedCompensationUnrecognizedCompensationCostsOnNonvestedAwards,
            "entityWideInformationRevenueFromExternalCustomerAmount" => owner.Facts.UsGaap.EntityWideInformationRevenueFromExternalCustomerAmount,
            "equityMethodInvestmentDividendsOrDistributions" => owner.Facts.UsGaap.EquityMethodInvestmentDividendsOrDistributions,
            "excessTaxBenefitFromShareBasedCompensationFinancingActivities" => owner.Facts.UsGaap.ExcessTaxBenefitFromShareBasedCompensationFinancingActivities,
            "excessTaxBenefitFromShareBasedCompensationOperatingActivities" => owner.Facts.UsGaap.ExcessTaxBenefitFromShareBasedCompensationOperatingActivities,
            "extraordinaryItemGainOrLossNetOfTaxAttributableToNoncontrollingInterest" => owner.Facts.UsGaap.ExtraordinaryItemGainOrLossNetOfTaxAttributableToNoncontrollingInterest,
            "extraordinaryItemGainOrLossNetOfTaxAttributableToReportingEntity" => owner.Facts.UsGaap.ExtraordinaryItemGainOrLossNetOfTaxAttributableToReportingEntity,
            "extraordinaryItemNetOfTax" => owner.Facts.UsGaap.ExtraordinaryItemNetOfTax,
            "extraordinaryItemsGross" => owner.Facts.UsGaap.ExtraordinaryItemsGross,
            "fairValueFinancialAssetsMeasuredOnRecurringBasisCashSurrenderValue" => owner.Facts.UsGaap.FairValueFinancialAssetsMeasuredOnRecurringBasisCashSurrenderValue,
            "fairValueInputsControlPremium" => owner.Facts.UsGaap.FairValueInputsControlPremium,
            "fairValueInputsDiscountRate" => owner.Facts.UsGaap.FairValueInputsDiscountRate,
            "financeLeaseInterestExpense" => owner.Facts.UsGaap.FinanceLeaseInterestExpense,
            "financeLeaseInterestPaymentOnLiability" => owner.Facts.UsGaap.FinanceLeaseInterestPaymentOnLiability,
            "financeLeaseLiability" => owner.Facts.UsGaap.FinanceLeaseLiability,
            "financeLeaseLiabilityCurrent" => owner.Facts.UsGaap.FinanceLeaseLiabilityCurrent,
            "financeLeaseLiabilityNoncurrent" => owner.Facts.UsGaap.FinanceLeaseLiabilityNoncurrent,
            "financeLeaseLiabilityPaymentsDue" => owner.Facts.UsGaap.FinanceLeaseLiabilityPaymentsDue,
            "financeLeaseLiabilityPaymentsDueAfterYearFive" => owner.Facts.UsGaap.FinanceLeaseLiabilityPaymentsDueAfterYearFive,
            "financeLeaseLiabilityPaymentsDueNextTwelveMonths" => owner.Facts.UsGaap.FinanceLeaseLiabilityPaymentsDueNextTwelveMonths,
            "financeLeaseLiabilityPaymentsDueYearFive" => owner.Facts.UsGaap.FinanceLeaseLiabilityPaymentsDueYearFive,
            "financeLeaseLiabilityPaymentsDueYearFour" => owner.Facts.UsGaap.FinanceLeaseLiabilityPaymentsDueYearFour,
            "financeLeaseLiabilityPaymentsDueYearThree" => owner.Facts.UsGaap.FinanceLeaseLiabilityPaymentsDueYearThree,
            "financeLeaseLiabilityPaymentsDueYearTwo" => owner.Facts.UsGaap.FinanceLeaseLiabilityPaymentsDueYearTwo,
            "financeLeaseLiabilityPaymentsRemainderOfFiscalYear" => owner.Facts.UsGaap.FinanceLeaseLiabilityPaymentsRemainderOfFiscalYear,
            "financeLeaseLiabilityUndiscountedExcessAmount" => owner.Facts.UsGaap.FinanceLeaseLiabilityUndiscountedExcessAmount,
            "financeLeasePrincipalPayments" => owner.Facts.UsGaap.FinanceLeasePrincipalPayments,
            "financeLeaseRightOfUseAsset" => owner.Facts.UsGaap.FinanceLeaseRightOfUseAsset,
            "financeLeaseRightOfUseAssetAmortization" => owner.Facts.UsGaap.FinanceLeaseRightOfUseAssetAmortization,
            "financeLeaseWeightedAverageDiscountRatePercent" => owner.Facts.UsGaap.FinanceLeaseWeightedAverageDiscountRatePercent,
            "financingReceivableAllowanceForCreditLosses" => owner.Facts.UsGaap.FinancingReceivableAllowanceForCreditLosses,
            "financingReceivableAllowanceForCreditLossesRecovery" => owner.Facts.UsGaap.FinancingReceivableAllowanceForCreditLossesRecovery,
            "financingReceivableAllowanceForCreditLossesWriteOffs" => owner.Facts.UsGaap.FinancingReceivableAllowanceForCreditLossesWriteOffs,
            "financingReceivableAllowanceForCreditLossForeignCurrencyTranslation" => owner.Facts.UsGaap.FinancingReceivableAllowanceForCreditLossForeignCurrencyTranslation,
            "finiteLivedCustomerListsGross" => owner.Facts.UsGaap.FiniteLivedCustomerListsGross,
            "finiteLivedIntangibleAssetsAmortizationExpense" => owner.Facts.UsGaap.FiniteLivedIntangibleAssetsAmortizationExpense,
            "finiteLivedIntangibleAssetsAmortizationExpenseNextTwelveMonths" => owner.Facts.UsGaap.FiniteLivedIntangibleAssetsAmortizationExpenseNextTwelveMonths,
            "finiteLivedIntangibleAssetsAmortizationExpenseRemainderOfFiscalYear" => owner.Facts.UsGaap.FiniteLivedIntangibleAssetsAmortizationExpenseRemainderOfFiscalYear,
            "finiteLivedIntangibleAssetsAmortizationExpenseYearFive" => owner.Facts.UsGaap.FiniteLivedIntangibleAssetsAmortizationExpenseYearFive,
            "finiteLivedIntangibleAssetsAmortizationExpenseYearFour" => owner.Facts.UsGaap.FiniteLivedIntangibleAssetsAmortizationExpenseYearFour,
            "finiteLivedIntangibleAssetsAmortizationExpenseYearThree" => owner.Facts.UsGaap.FiniteLivedIntangibleAssetsAmortizationExpenseYearThree,
            "finiteLivedIntangibleAssetsAmortizationExpenseYearTwo" => owner.Facts.UsGaap.FiniteLivedIntangibleAssetsAmortizationExpenseYearTwo,
            "finiteLivedIntangibleAssetsNet" => owner.Facts.UsGaap.FiniteLivedIntangibleAssetsNet,
            "futureAmortizationExpenseYearFive" => owner.Facts.UsGaap.FutureAmortizationExpenseYearFive,
            "futureAmortizationExpenseYearFour" => owner.Facts.UsGaap.FutureAmortizationExpenseYearFour,
            "futureAmortizationExpenseYearOne" => owner.Facts.UsGaap.FutureAmortizationExpenseYearOne,
            "futureAmortizationExpenseYearThree" => owner.Facts.UsGaap.FutureAmortizationExpenseYearThree,
            "futureAmortizationExpenseYearTwo" => owner.Facts.UsGaap.FutureAmortizationExpenseYearTwo,
            "gainLossOnDispositionOfIntangibleAssets" => owner.Facts.UsGaap.GainLossOnDispositionOfIntangibleAssets,
            "gainLossOnSaleOfBusiness" => owner.Facts.UsGaap.GainLossOnSaleOfBusiness,
            "gainLossOnSaleOfInvestments" => owner.Facts.UsGaap.GainLossOnSaleOfInvestments,
            "gainLossOnSaleOfOtherAssets" => owner.Facts.UsGaap.GainLossOnSaleOfOtherAssets,
            "gainLossRelatedToLitigationSettlement" => owner.Facts.UsGaap.GainLossRelatedToLitigationSettlement,
            "gainsLossesOnExtinguishmentOfDebt" => owner.Facts.UsGaap.GainsLossesOnExtinguishmentOfDebt,
            "goodwill" => owner.Facts.UsGaap.Goodwill,
            "goodwillAcquiredDuringPeriod" => owner.Facts.UsGaap.GoodwillAcquiredDuringPeriod,
            "goodwillForeignCurrencyTranslationGainLoss" => owner.Facts.UsGaap.GoodwillForeignCurrencyTranslationGainLoss,
            "goodwillImpairedAccumulatedImpairmentLoss" => owner.Facts.UsGaap.GoodwillImpairedAccumulatedImpairmentLoss,
            "goodwillImpairmentLoss" => owner.Facts.UsGaap.GoodwillImpairmentLoss,
            "goodwillPurchaseAccountingAdjustments" => owner.Facts.UsGaap.GoodwillPurchaseAccountingAdjustments,
            "goodwillTransfers" => owner.Facts.UsGaap.GoodwillTransfers,
            "impairmentOfIntangibleAssetsIndefinitelivedExcludingGoodwill" => owner.Facts.UsGaap.ImpairmentOfIntangibleAssetsIndefinitelivedExcludingGoodwill,
            "impairmentOfLongLivedAssetsToBeDisposedOf" => owner.Facts.UsGaap.ImpairmentOfLongLivedAssetsToBeDisposedOf,
            "incomeLossBeforeExtraordinaryItemsAndCumulativeEffectOfChangeInAccountingPrinciple" => owner.Facts.UsGaap.IncomeLossBeforeExtraordinaryItemsAndCumulativeEffectOfChangeInAccountingPrinciple,
            "incomeLossBeforeExtraordinaryItemsAndCumulativeEffectOfChangeInAccountingPrinciplePerBasicShare" => owner.Facts.UsGaap.IncomeLossBeforeExtraordinaryItemsAndCumulativeEffectOfChangeInAccountingPrinciplePerBasicShare,
            "incomeLossBeforeExtraordinaryItemsAndCumulativeEffectOfChangeInAccountingPrinciplePerDilutedShare" => owner.Facts.UsGaap.IncomeLossBeforeExtraordinaryItemsAndCumulativeEffectOfChangeInAccountingPrinciplePerDilutedShare,
            "incomeLossFromContinuingOperations" => owner.Facts.UsGaap.IncomeLossFromContinuingOperations,
            "incomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest" => owner.Facts.UsGaap.IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest,
            "incomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments" => owner.Facts.UsGaap.IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments,
            "incomeLossFromEquityMethodInvestments" => owner.Facts.UsGaap.IncomeLossFromEquityMethodInvestments,
            "incomeLossFromExtraordinaryItemsNetOfTaxPerBasicAndDilutedShare" => owner.Facts.UsGaap.IncomeLossFromExtraordinaryItemsNetOfTaxPerBasicAndDilutedShare,
            "incomeLossFromExtraordinaryItemsNetOfTaxPerBasicShare" => owner.Facts.UsGaap.IncomeLossFromExtraordinaryItemsNetOfTaxPerBasicShare,
            "incomeLossFromExtraordinaryItemsNetOfTaxPerDilutedShare" => owner.Facts.UsGaap.IncomeLossFromExtraordinaryItemsNetOfTaxPerDilutedShare,
            "incomeLossFromOperationsBeforeExtraordinaryItemsPerBasicAndDilutedShare" => owner.Facts.UsGaap.IncomeLossFromOperationsBeforeExtraordinaryItemsPerBasicAndDilutedShare,
            "incomeTaxEffectsAllocatedDirectlyToEquityEmployeeStockOptions" => owner.Facts.UsGaap.IncomeTaxEffectsAllocatedDirectlyToEquityEmployeeStockOptions,
            "incomeTaxExpenseBenefit" => owner.Facts.UsGaap.IncomeTaxExpenseBenefit,
            "incomeTaxExpenseBenefitContinuingOperations" => owner.Facts.UsGaap.IncomeTaxExpenseBenefitContinuingOperations,
            "incomeTaxExpenseBenefitExtraordinaryItems" => owner.Facts.UsGaap.IncomeTaxExpenseBenefitExtraordinaryItems,
            "incomeTaxesPaid" => owner.Facts.UsGaap.IncomeTaxesPaid,
            "incomeTaxesPaidNet" => owner.Facts.UsGaap.IncomeTaxesPaidNet,
            "incomeTaxesReceivable" => owner.Facts.UsGaap.IncomeTaxesReceivable,
            "incomeTaxReceivable" => owner.Facts.UsGaap.IncomeTaxReceivable,
            "incomeTaxReconciliationChangeInDeferredTaxAssetsValuationAllowance" => owner.Facts.UsGaap.IncomeTaxReconciliationChangeInDeferredTaxAssetsValuationAllowance,
            "incomeTaxReconciliationDeductionsDividends" => owner.Facts.UsGaap.IncomeTaxReconciliationDeductionsDividends,
            "incomeTaxReconciliationDeductionsOther" => owner.Facts.UsGaap.IncomeTaxReconciliationDeductionsOther,
            "incomeTaxReconciliationDispositionOfAssets" => owner.Facts.UsGaap.IncomeTaxReconciliationDispositionOfAssets,
            "incomeTaxReconciliationNondeductibleExpense" => owner.Facts.UsGaap.IncomeTaxReconciliationNondeductibleExpense,
            "incomeTaxReconciliationNondeductibleExpenseImpairmentLosses" => owner.Facts.UsGaap.IncomeTaxReconciliationNondeductibleExpenseImpairmentLosses,
            "incomeTaxReconciliationNondeductibleExpenseLifeInsurance" => owner.Facts.UsGaap.IncomeTaxReconciliationNondeductibleExpenseLifeInsurance,
            "incomeTaxReconciliationOtherAdjustments" => owner.Facts.UsGaap.IncomeTaxReconciliationOtherAdjustments,
            "incomeTaxReconciliationTaxContingencies" => owner.Facts.UsGaap.IncomeTaxReconciliationTaxContingencies,
            "incomeTaxReconciliationTaxContingenciesStateAndLocal" => owner.Facts.UsGaap.IncomeTaxReconciliationTaxContingenciesStateAndLocal,
            "incomeTaxReconciliationTaxCreditsResearch" => owner.Facts.UsGaap.IncomeTaxReconciliationTaxCreditsResearch,
            "incomeTaxReconciliationTaxSettlements" => owner.Facts.UsGaap.IncomeTaxReconciliationTaxSettlements,
            "incomeTaxReconciliationTaxSettlementsDomestic" => owner.Facts.UsGaap.IncomeTaxReconciliationTaxSettlementsDomestic,
            "increaseDecreaseInAccountsPayable" => owner.Facts.UsGaap.IncreaseDecreaseInAccountsPayable,
            "increaseDecreaseInAccountsReceivable" => owner.Facts.UsGaap.IncreaseDecreaseInAccountsReceivable,
            "increaseDecreaseInAccruedTaxesPayable" => owner.Facts.UsGaap.IncreaseDecreaseInAccruedTaxesPayable,
            "increaseDecreaseInOtherCurrentAssets" => owner.Facts.UsGaap.IncreaseDecreaseInOtherCurrentAssets,
            "increaseDecreaseInOtherCurrentAssetsAndLiabilitiesNet" => owner.Facts.UsGaap.IncreaseDecreaseInOtherCurrentAssetsAndLiabilitiesNet,
            "increaseDecreaseInOtherNoncurrentAssetsAndLiabilitiesNet" => owner.Facts.UsGaap.IncreaseDecreaseInOtherNoncurrentAssetsAndLiabilitiesNet,
            "increaseDecreaseInOtherOperatingCapitalNet" => owner.Facts.UsGaap.IncreaseDecreaseInOtherOperatingCapitalNet,
            "increaseDecreaseInPensionAndPostretirementObligations" => owner.Facts.UsGaap.IncreaseDecreaseInPensionAndPostretirementObligations,
            "incrementalCommonSharesAttributableToConversionOfDebtSecurities" => owner.Facts.UsGaap.IncrementalCommonSharesAttributableToConversionOfDebtSecurities,
            "incrementalCommonSharesAttributableToShareBasedPaymentArrangements" => owner.Facts.UsGaap.IncrementalCommonSharesAttributableToShareBasedPaymentArrangements,
            "indefiniteLivedIntangibleAssetsExcludingGoodwill" => owner.Facts.UsGaap.IndefiniteLivedIntangibleAssetsExcludingGoodwill,
            "intangibleAssetsNetExcludingGoodwill" => owner.Facts.UsGaap.IntangibleAssetsNetExcludingGoodwill,
            "intangibleAssetsNetIncludingGoodwill" => owner.Facts.UsGaap.IntangibleAssetsNetIncludingGoodwill,
            "interestAndDividendsPayableCurrent" => owner.Facts.UsGaap.InterestAndDividendsPayableCurrent,
            "interestCostsCapitalized" => owner.Facts.UsGaap.InterestCostsCapitalized,
            "interestCostsIncurred" => owner.Facts.UsGaap.InterestCostsIncurred,
            "interestExpense" => owner.Facts.UsGaap.InterestExpense,
            "interestExpenseDebt" => owner.Facts.UsGaap.InterestExpenseDebt,
            "interestPaidCapitalized" => owner.Facts.UsGaap.InterestPaidCapitalized,
            "interestPaidNet" => owner.Facts.UsGaap.InterestPaidNet,
            "interestPayableCurrent" => owner.Facts.UsGaap.InterestPayableCurrent,
            "inventoryNet" => owner.Facts.UsGaap.InventoryNet,
            "leaseAndRentalExpense" => owner.Facts.UsGaap.LeaseAndRentalExpense,
            "leaseCost" => owner.Facts.UsGaap.LeaseCost,
            "lesseeOperatingLeaseLiabilityPaymentsDue" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsDue,
            "lesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive,
            "lesseeOperatingLeaseLiabilityPaymentsDueNextRollingTwelveMonths" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsDueNextRollingTwelveMonths,
            "lesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths,
            "lesseeOperatingLeaseLiabilityPaymentsDueYearFive" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsDueYearFive,
            "lesseeOperatingLeaseLiabilityPaymentsDueYearFour" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsDueYearFour,
            "lesseeOperatingLeaseLiabilityPaymentsDueYearThree" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsDueYearThree,
            "lesseeOperatingLeaseLiabilityPaymentsDueYearTwo" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsDueYearTwo,
            "lesseeOperatingLeaseLiabilityPaymentsRemainderOfFiscalYear" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityPaymentsRemainderOfFiscalYear,
            "lesseeOperatingLeaseLiabilityUndiscountedExcessAmount" => owner.Facts.UsGaap.LesseeOperatingLeaseLiabilityUndiscountedExcessAmount,
            "lettersOfCreditOutstandingAmount" => owner.Facts.UsGaap.LettersOfCreditOutstandingAmount,
            "liabilitiesAndStockholdersEquity" => owner.Facts.UsGaap.LiabilitiesAndStockholdersEquity,
            "liabilitiesCurrent" => owner.Facts.UsGaap.LiabilitiesCurrent,
            "liabilitiesOfDisposalGroupIncludingDiscontinuedOperationCurrent" => owner.Facts.UsGaap.LiabilitiesOfDisposalGroupIncludingDiscontinuedOperationCurrent,
            "liabilitiesOtherThanLongtermDebtNoncurrent" => owner.Facts.UsGaap.LiabilitiesOtherThanLongtermDebtNoncurrent,
            "liabilityForUncertainTaxPositionsNoncurrent" => owner.Facts.UsGaap.LiabilityForUncertainTaxPositionsNoncurrent,
            "litigationReserve" => owner.Facts.UsGaap.LitigationReserve,
            "litigationReserveCurrent" => owner.Facts.UsGaap.LitigationReserveCurrent,
            "longTermDebt" => owner.Facts.UsGaap.LongTermDebt,
            "longTermDebtAndCapitalLeaseObligations" => owner.Facts.UsGaap.LongTermDebtAndCapitalLeaseObligations,
            "longTermDebtAndCapitalLeaseObligationsCurrent" => owner.Facts.UsGaap.LongTermDebtAndCapitalLeaseObligationsCurrent,
            "longTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities" => owner.Facts.UsGaap.LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities,
            "longTermDebtCurrent" => owner.Facts.UsGaap.LongTermDebtCurrent,
            "longTermDebtMaturitiesRepaymentsOfPrincipalAfterYearFive" => owner.Facts.UsGaap.LongTermDebtMaturitiesRepaymentsOfPrincipalAfterYearFive,
            "longTermDebtMaturitiesRepaymentsOfPrincipalInNextTwelveMonths" => owner.Facts.UsGaap.LongTermDebtMaturitiesRepaymentsOfPrincipalInNextTwelveMonths,
            "longTermDebtMaturitiesRepaymentsOfPrincipalInYearFive" => owner.Facts.UsGaap.LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFive,
            "longTermDebtMaturitiesRepaymentsOfPrincipalInYearFour" => owner.Facts.UsGaap.LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFour,
            "longTermDebtMaturitiesRepaymentsOfPrincipalInYearThree" => owner.Facts.UsGaap.LongTermDebtMaturitiesRepaymentsOfPrincipalInYearThree,
            "longTermDebtMaturitiesRepaymentsOfPrincipalInYearTwo" => owner.Facts.UsGaap.LongTermDebtMaturitiesRepaymentsOfPrincipalInYearTwo,
            "longTermDebtMaturitiesRepaymentsOfPrincipalRemainderOfFiscalYear" => owner.Facts.UsGaap.LongTermDebtMaturitiesRepaymentsOfPrincipalRemainderOfFiscalYear,
            "lossContingencyEstimateOfPossibleLoss" => owner.Facts.UsGaap.LossContingencyEstimateOfPossibleLoss,
            "lossContingencyNewClaimsFiledNumber" => owner.Facts.UsGaap.LossContingencyNewClaimsFiledNumber,
            "lossContingencyNumberOfPlaintiffs" => owner.Facts.UsGaap.LossContingencyNumberOfPlaintiffs,
            "lossContingencyPatentsAllegedlyInfringedNumber" => owner.Facts.UsGaap.LossContingencyPatentsAllegedlyInfringedNumber,
            "marketableSecuritiesRealizedGainLoss" => owner.Facts.UsGaap.MarketableSecuritiesRealizedGainLoss,
            "materialsSuppliesAndOther" => owner.Facts.UsGaap.MaterialsSuppliesAndOther,
            "minorityInterest" => owner.Facts.UsGaap.MinorityInterest,
            "minorityInterestDecreaseFromDistributionsToNoncontrollingInterestHolders" => owner.Facts.UsGaap.MinorityInterestDecreaseFromDistributionsToNoncontrollingInterestHolders,
            "minorityInterestInNetIncomeLossJointVenturePartners" => owner.Facts.UsGaap.MinorityInterestInNetIncomeLossJointVenturePartners,
            "netCashProvidedByUsedInContinuingOperations" => owner.Facts.UsGaap.NetCashProvidedByUsedInContinuingOperations,
            "netCashProvidedByUsedInFinancingActivities" => owner.Facts.UsGaap.NetCashProvidedByUsedInFinancingActivities,
            "netCashProvidedByUsedInFinancingActivitiesContinuingOperations" => owner.Facts.UsGaap.NetCashProvidedByUsedInFinancingActivitiesContinuingOperations,
            "netCashProvidedByUsedInInvestingActivities" => owner.Facts.UsGaap.NetCashProvidedByUsedInInvestingActivities,
            "netCashProvidedByUsedInInvestingActivitiesContinuingOperations" => owner.Facts.UsGaap.NetCashProvidedByUsedInInvestingActivitiesContinuingOperations,
            "netCashProvidedByUsedInOperatingActivities" => owner.Facts.UsGaap.NetCashProvidedByUsedInOperatingActivities,
            "netCashProvidedByUsedInOperatingActivitiesContinuingOperations" => owner.Facts.UsGaap.NetCashProvidedByUsedInOperatingActivitiesContinuingOperations,
            "netIncomeLoss" => owner.Facts.UsGaap.NetIncomeLoss,
            "netIncomeLossAttributableToNoncontrollingInterest" => owner.Facts.UsGaap.NetIncomeLossAttributableToNoncontrollingInterest,
            "netIncomeLossAvailableToCommonStockholdersBasic" => owner.Facts.UsGaap.NetIncomeLossAvailableToCommonStockholdersBasic,
            "netIncomeLossAvailableToCommonStockholdersDiluted" => owner.Facts.UsGaap.NetIncomeLossAvailableToCommonStockholdersDiluted,
            "nonoperatingIncomeExpense" => owner.Facts.UsGaap.NonoperatingIncomeExpense,
            "numberOfOperatingSegments" => owner.Facts.UsGaap.NumberOfOperatingSegments,
            "numberOfReportableSegments" => owner.Facts.UsGaap.NumberOfReportableSegments,
            "numberOfReportingUnits" => owner.Facts.UsGaap.NumberOfReportingUnits,
            "ociBeforeReclassificationsNetOfTaxAttributableToParent" => owner.Facts.UsGaap.OciBeforeReclassificationsNetOfTaxAttributableToParent,
            "operatingCostsAndExpenses" => owner.Facts.UsGaap.OperatingCostsAndExpenses,
            "operatingExpenses" => owner.Facts.UsGaap.OperatingExpenses,
            "operatingIncomeLoss" => owner.Facts.UsGaap.OperatingIncomeLoss,
            "operatingLeaseCost" => owner.Facts.UsGaap.OperatingLeaseCost,
            "operatingLeaseLeaseIncome" => owner.Facts.UsGaap.OperatingLeaseLeaseIncome,
            "operatingLeaseLiability" => owner.Facts.UsGaap.OperatingLeaseLiability,
            "operatingLeaseLiabilityCurrent" => owner.Facts.UsGaap.OperatingLeaseLiabilityCurrent,
            "operatingLeaseLiabilityNoncurrent" => owner.Facts.UsGaap.OperatingLeaseLiabilityNoncurrent,
            "operatingLeasePayments" => owner.Facts.UsGaap.OperatingLeasePayments,
            "operatingLeaseRightOfUseAsset" => owner.Facts.UsGaap.OperatingLeaseRightOfUseAsset,
            "operatingLeasesFutureMinimumPaymentsDue" => owner.Facts.UsGaap.OperatingLeasesFutureMinimumPaymentsDue,
            "operatingLeasesFutureMinimumPaymentsDueCurrent" => owner.Facts.UsGaap.OperatingLeasesFutureMinimumPaymentsDueCurrent,
            "operatingLeasesFutureMinimumPaymentsDueFutureMinimumSubleaseRentals" => owner.Facts.UsGaap.OperatingLeasesFutureMinimumPaymentsDueFutureMinimumSubleaseRentals,
            "operatingLeasesFutureMinimumPaymentsDueInFiveYears" => owner.Facts.UsGaap.OperatingLeasesFutureMinimumPaymentsDueInFiveYears,
            "operatingLeasesFutureMinimumPaymentsDueInFourYears" => owner.Facts.UsGaap.OperatingLeasesFutureMinimumPaymentsDueInFourYears,
            "operatingLeasesFutureMinimumPaymentsDueInThreeYears" => owner.Facts.UsGaap.OperatingLeasesFutureMinimumPaymentsDueInThreeYears,
            "operatingLeasesFutureMinimumPaymentsDueInTwoYears" => owner.Facts.UsGaap.OperatingLeasesFutureMinimumPaymentsDueInTwoYears,
            "operatingLeasesFutureMinimumPaymentsDueThereafter" => owner.Facts.UsGaap.OperatingLeasesFutureMinimumPaymentsDueThereafter,
            "operatingLeasesIncomeStatementSubleaseRevenue" => owner.Facts.UsGaap.OperatingLeasesIncomeStatementSubleaseRevenue,
            "operatingLeasesRentExpenseSubleaseRentals1" => owner.Facts.UsGaap.OperatingLeasesRentExpenseSubleaseRentals1,
            "operatingLeaseWeightedAverageDiscountRatePercent" => owner.Facts.UsGaap.OperatingLeaseWeightedAverageDiscountRatePercent,
            "operatingLossCarryforwards" => owner.Facts.UsGaap.OperatingLossCarryforwards,
            "operatingLossCarryforwardsValuationAllowance" => owner.Facts.UsGaap.OperatingLossCarryforwardsValuationAllowance,
            "otherAssetImpairmentCharges" => owner.Facts.UsGaap.OtherAssetImpairmentCharges,
            "otherAssets" => owner.Facts.UsGaap.OtherAssets,
            "otherAssetsCurrent" => owner.Facts.UsGaap.OtherAssetsCurrent,
            "otherAssetsMiscellaneousCurrent" => owner.Facts.UsGaap.OtherAssetsMiscellaneousCurrent,
            "otherAssetsNoncurrent" => owner.Facts.UsGaap.OtherAssetsNoncurrent,
            "otherComprehensiveIncomeAmortizationOfDefinedBenefitPlanNetPriorServiceCostRecognizedInNetPeriodicPensionCostNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeAmortizationOfDefinedBenefitPlanNetPriorServiceCostRecognizedInNetPeriodicPensionCostNetOfTax,
            "otherComprehensiveIncomeAmortizationOfDefinedBenefitPlanNetPriorServiceCostRecognizedInNetPeriodicPensionCostTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeAmortizationOfDefinedBenefitPlanNetPriorServiceCostRecognizedInNetPeriodicPensionCostTax,
            "otherComprehensiveIncomeAvailableforsaleSecuritiesAdjustmentNetOfTaxPortionAttributableToParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeAvailableforsaleSecuritiesAdjustmentNetOfTaxPortionAttributableToParent,
            "otherComprehensiveIncomeAvailableforsaleSecuritiesTaxPortionAttributableToParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeAvailableforsaleSecuritiesTaxPortionAttributableToParent,
            "otherComprehensiveIncomeDefinedBenefitPlanNetPriorServiceCostsArisingDuringPeriodTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeDefinedBenefitPlanNetPriorServiceCostsArisingDuringPeriodTax,
            "otherComprehensiveIncomeDefinedBenefitPlanNetPriorServiceCostsCreditArisingDuringPeriodNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeDefinedBenefitPlanNetPriorServiceCostsCreditArisingDuringPeriodNetOfTax,
            "otherComprehensiveIncomeDefinedBenefitPlansAdjustmentNetOfTaxPeriodIncreaseDecrease" => owner.Facts.UsGaap.OtherComprehensiveIncomeDefinedBenefitPlansAdjustmentNetOfTaxPeriodIncreaseDecrease,
            "otherComprehensiveIncomeDefinedBenefitPlansAdjustmentNetOfTaxPortionAttributableToParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeDefinedBenefitPlansAdjustmentNetOfTaxPortionAttributableToParent,
            "otherComprehensiveIncomeDefinedBenefitPlansNetUnamortizedGainLossArisingDuringPeriodNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeDefinedBenefitPlansNetUnamortizedGainLossArisingDuringPeriodNetOfTax,
            "otherComprehensiveIncomeDefinedBenefitPlansNetUnamortizedGainLossArisingDuringPeriodTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeDefinedBenefitPlansNetUnamortizedGainLossArisingDuringPeriodTax,
            "otherComprehensiveIncomeDefinedBenefitPlansTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeDefinedBenefitPlansTax,
            "otherComprehensiveIncomeDefinedBenefitPlansTaxPortionAttributableToParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeDefinedBenefitPlansTaxPortionAttributableToParent,
            "otherComprehensiveIncomeDerivativesQualifyingAsHedgesNetOfTaxPeriodIncreaseDecrease" => owner.Facts.UsGaap.OtherComprehensiveIncomeDerivativesQualifyingAsHedgesNetOfTaxPeriodIncreaseDecrease,
            "otherComprehensiveIncomeDerivativesQualifyingAsHedgesNetOfTaxPortionAttributableToParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeDerivativesQualifyingAsHedgesNetOfTaxPortionAttributableToParent,
            "otherComprehensiveIncomeFinalizationOfPensionAndNonPensionPostretirementPlanValuationTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeFinalizationOfPensionAndNonPensionPostretirementPlanValuationTax,
            "otherComprehensiveIncomeForeignCurrencyTransactionAndTranslationAdjustmentNetOfTaxPortionAttributableToParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeForeignCurrencyTransactionAndTranslationAdjustmentNetOfTaxPortionAttributableToParent,
            "otherComprehensiveIncomeForeignCurrencyTranslationAdjustmentTaxPortionAttributableToParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeForeignCurrencyTranslationAdjustmentTaxPortionAttributableToParent,
            "otherComprehensiveIncomeLossAmortizationAdjustmentFromAOCIPensionAndOtherPostretirementBenefitPlansForNetPriorServiceCostCreditNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossAmortizationAdjustmentFromAOCIPensionAndOtherPostretirementBenefitPlansForNetPriorServiceCostCreditNetOfTax,
            "otherComprehensiveIncomeLossAmortizationAdjustmentFromAOCIPensionAndOtherPostretirementBenefitPlansForNetPriorServiceCostCreditTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossAmortizationAdjustmentFromAOCIPensionAndOtherPostretirementBenefitPlansForNetPriorServiceCostCreditTax,
            "otherComprehensiveIncomeLossAmortizationPensionAndOtherPostretirementBenefitPlansNetPriorServiceCostRecognizedInNetPeriodicPensionCostTaxEffect" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossAmortizationPensionAndOtherPostretirementBenefitPlansNetPriorServiceCostRecognizedInNetPeriodicPensionCostTaxEffect,
            "otherComprehensiveIncomeLossBeforeReclassificationsNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossBeforeReclassificationsNetOfTax,
            "otherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationAndTaxParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationAndTaxParent,
            "otherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationTax,
            "otherComprehensiveIncomeLossCashFlowHedgeGainLossReclassificationAfterTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossCashFlowHedgeGainLossReclassificationAfterTax,
            "otherComprehensiveIncomeLossCashFlowHedgeGainLossReclassificationTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossCashFlowHedgeGainLossReclassificationTax,
            "otherComprehensiveIncomeLossDerivativesQualifyingAsHedgesNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossDerivativesQualifyingAsHedgesNetOfTax,
            "otherComprehensiveIncomeLossDerivativesQualifyingAsHedgesTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossDerivativesQualifyingAsHedgesTax,
            "otherComprehensiveIncomeLossFinalizationOfPensionAndNonPensionPostretirementPlanValuationNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossFinalizationOfPensionAndNonPensionPostretirementPlanValuationNetOfTax,
            "otherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax,
            "otherComprehensiveIncomeLossForeignCurrencyTranslationAdjustmentTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossForeignCurrencyTranslationAdjustmentTax,
            "otherComprehensiveIncomeLossNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossNetOfTax,
            "otherComprehensiveIncomeLossNetOfTaxPeriodIncreaseDecrease" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossNetOfTaxPeriodIncreaseDecrease,
            "otherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent,
            "otherComprehensiveIncomeLossPensionAndOtherPostretirementBenefitPlansBenefitPlanImprovementTaxEffect" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossPensionAndOtherPostretirementBenefitPlansBenefitPlanImprovementTaxEffect,
            "otherComprehensiveIncomeLossReclassificationAdjustmentForSaleOfSecuritiesIncludedInNetIncomeNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossReclassificationAdjustmentForSaleOfSecuritiesIncludedInNetIncomeNetOfTax,
            "otherComprehensiveIncomeLossReclassificationAdjustmentForSaleOfSecuritiesIncludedInNetIncomeTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossReclassificationAdjustmentForSaleOfSecuritiesIncludedInNetIncomeTax,
            "otherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIForSaleOfSecuritiesNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIForSaleOfSecuritiesNetOfTax,
            "otherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIForSaleOfSecuritiesTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIForSaleOfSecuritiesTax,
            "otherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIOnDerivativesNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIOnDerivativesNetOfTax,
            "otherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIPensionAndOtherPostretirementBenefitPlansForNetGainLossNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIPensionAndOtherPostretirementBenefitPlansForNetGainLossNetOfTax,
            "otherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIPensionAndOtherPostretirementBenefitPlansForNetGainLossTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIPensionAndOtherPostretirementBenefitPlansForNetGainLossTax,
            "otherComprehensiveIncomeLossTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossTax,
            "otherComprehensiveIncomeReclassificationAdjustmentForHeldToMaturityTransferredToAvailableForSaleSecuritiesNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeReclassificationAdjustmentForHeldToMaturityTransferredToAvailableForSaleSecuritiesNetOfTax,
            "otherComprehensiveIncomeReclassificationAdjustmentForHeldToMaturityTransferredToAvailableForSaleSecuritiesTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeReclassificationAdjustmentForHeldToMaturityTransferredToAvailableForSaleSecuritiesTax,
            "otherComprehensiveIncomeReclassificationAdjustmentForSaleOfSecuritiesIncludedInNetIncomeNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeReclassificationAdjustmentForSaleOfSecuritiesIncludedInNetIncomeNetOfTax,
            "otherComprehensiveIncomeReclassificationAdjustmentForSaleOfSecuritiesIncludedInNetIncomeTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeReclassificationAdjustmentForSaleOfSecuritiesIncludedInNetIncomeTax,
            "otherComprehensiveIncomeReclassificationAdjustmentOnDerivativesIncludedInNetIncomeNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeReclassificationAdjustmentOnDerivativesIncludedInNetIncomeNetOfTax,
            "otherComprehensiveIncomeReclassificationAdjustmentOnDerivativesIncludedInNetIncomeTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeReclassificationAdjustmentOnDerivativesIncludedInNetIncomeTax,
            "otherComprehensiveIncomeReclassificationOfDefinedBenefitPlansNetGainLossRecognizedInNetPeriodicBenefitCostNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeReclassificationOfDefinedBenefitPlansNetGainLossRecognizedInNetPeriodicBenefitCostNetOfTax,
            "otherComprehensiveIncomeReclassificationOfDefinedBenefitPlansNetGainLossRecognizedInNetPeriodicBenefitCostTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeReclassificationOfDefinedBenefitPlansNetGainLossRecognizedInNetPeriodicBenefitCostTax,
            "otherComprehensiveIncomeUnrealizedGainLossOnDerivativesArisingDuringPeriodNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeUnrealizedGainLossOnDerivativesArisingDuringPeriodNetOfTax,
            "otherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodNetOfTax,
            "otherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodTax,
            "otherDeferredCostsNet" => owner.Facts.UsGaap.OtherDeferredCostsNet,
            "otherDeferredCreditsNoncurrent" => owner.Facts.UsGaap.OtherDeferredCreditsNoncurrent,
            "otherFiniteLivedIntangibleAssetsGross" => owner.Facts.UsGaap.OtherFiniteLivedIntangibleAssetsGross,
            "otherIntangibleAssetsNet" => owner.Facts.UsGaap.OtherIntangibleAssetsNet,
            "otherLiabilitiesCurrent" => owner.Facts.UsGaap.OtherLiabilitiesCurrent,
            "otherLiabilitiesNoncurrent" => owner.Facts.UsGaap.OtherLiabilitiesNoncurrent,
            "otherNonoperatingIncomeExpense" => owner.Facts.UsGaap.OtherNonoperatingIncomeExpense,
            "otherOperatingActivitiesCashFlowStatement" => owner.Facts.UsGaap.OtherOperatingActivitiesCashFlowStatement,
            "otherPaymentsToAcquireBusinesses" => owner.Facts.UsGaap.OtherPaymentsToAcquireBusinesses,
            "otherPostretirementDefinedBenefitPlanLiabilitiesNoncurrent" => owner.Facts.UsGaap.OtherPostretirementDefinedBenefitPlanLiabilitiesNoncurrent,
            "otherReceivablesGrossCurrent" => owner.Facts.UsGaap.OtherReceivablesGrossCurrent,
            "otherSundryLiabilitiesCurrent" => owner.Facts.UsGaap.OtherSundryLiabilitiesCurrent,
            "paymentsForOtherOperatingActivities" => owner.Facts.UsGaap.PaymentsForOtherOperatingActivities,
            "paymentsForProceedsFromHedgeInvestingActivities" => owner.Facts.UsGaap.PaymentsForProceedsFromHedgeInvestingActivities,
            "paymentsForProceedsFromInvestments" => owner.Facts.UsGaap.PaymentsForProceedsFromInvestments,
            "paymentsForProceedsFromOtherInvestingActivities" => owner.Facts.UsGaap.PaymentsForProceedsFromOtherInvestingActivities,
            "paymentsForRepurchaseOfCommonStock" => owner.Facts.UsGaap.PaymentsForRepurchaseOfCommonStock,
            "paymentsForRestructuring" => owner.Facts.UsGaap.PaymentsForRestructuring,
            "paymentsOfDebtExtinguishmentCosts" => owner.Facts.UsGaap.PaymentsOfDebtExtinguishmentCosts,
            "paymentsOfDividends" => owner.Facts.UsGaap.PaymentsOfDividends,
            "paymentsOfDividendsCommonStock" => owner.Facts.UsGaap.PaymentsOfDividendsCommonStock,
            "paymentsToAcquireBusinessesGross" => owner.Facts.UsGaap.PaymentsToAcquireBusinessesGross,
            "paymentsToAcquireBusinessesNetOfCashAcquired" => owner.Facts.UsGaap.PaymentsToAcquireBusinessesNetOfCashAcquired,
            "paymentsToAcquireBusinessTwoNetOfCashAcquired" => owner.Facts.UsGaap.PaymentsToAcquireBusinessTwoNetOfCashAcquired,
            "paymentsToAcquireProductiveAssets" => owner.Facts.UsGaap.PaymentsToAcquireProductiveAssets,
            "paymentsToAcquirePropertyPlantAndEquipment" => owner.Facts.UsGaap.PaymentsToAcquirePropertyPlantAndEquipment,
            "pensionAndOtherPostretirementDefinedBenefitPlansLiabilitiesNoncurrent" => owner.Facts.UsGaap.PensionAndOtherPostretirementDefinedBenefitPlansLiabilitiesNoncurrent,
            "postemploymentBenefitsLiabilityNoncurrent" => owner.Facts.UsGaap.PostemploymentBenefitsLiabilityNoncurrent,
            "preferredStockDividends" => owner.Facts.UsGaap.PreferredStockDividends,
            "preferredStockDividendsPerShareDeclared" => owner.Facts.UsGaap.PreferredStockDividendsPerShareDeclared,
            "preferredStockParOrStatedValuePerShare" => owner.Facts.UsGaap.PreferredStockParOrStatedValuePerShare,
            "preferredStockSharesAuthorized" => owner.Facts.UsGaap.PreferredStockSharesAuthorized,
            "preferredStockSharesIssued" => owner.Facts.UsGaap.PreferredStockSharesIssued,
            "preferredStockSharesOutstanding" => owner.Facts.UsGaap.PreferredStockSharesOutstanding,
            "preferredStockValue" => owner.Facts.UsGaap.PreferredStockValue,
            "prepaidExpenseCurrent" => owner.Facts.UsGaap.PrepaidExpenseCurrent,
            "prescriptionDrugSubsidyReceiptsAfterYearFive" => owner.Facts.UsGaap.PrescriptionDrugSubsidyReceiptsAfterYearFive,
            "prescriptionDrugSubsidyReceiptsNextTwelveMonths" => owner.Facts.UsGaap.PrescriptionDrugSubsidyReceiptsNextTwelveMonths,
            "prescriptionDrugSubsidyReceiptsYearFive1" => owner.Facts.UsGaap.PrescriptionDrugSubsidyReceiptsYearFive1,
            "prescriptionDrugSubsidyReceiptsYearFour1" => owner.Facts.UsGaap.PrescriptionDrugSubsidyReceiptsYearFour1,
            "prescriptionDrugSubsidyReceiptsYearThree1" => owner.Facts.UsGaap.PrescriptionDrugSubsidyReceiptsYearThree1,
            "prescriptionDrugSubsidyReceiptsYearTwo1" => owner.Facts.UsGaap.PrescriptionDrugSubsidyReceiptsYearTwo1,
            "priorPeriodReclassificationAdjustment" => owner.Facts.UsGaap.PriorPeriodReclassificationAdjustment,
            "proceedsFromDivestitureOfBusinesses" => owner.Facts.UsGaap.ProceedsFromDivestitureOfBusinesses,
            "proceedsFromIncomeTaxRefunds" => owner.Facts.UsGaap.ProceedsFromIncomeTaxRefunds,
            "proceedsFromIssuanceOfCommonStock" => owner.Facts.UsGaap.ProceedsFromIssuanceOfCommonStock,
            "proceedsFromIssuanceOfLongTermDebt" => owner.Facts.UsGaap.ProceedsFromIssuanceOfLongTermDebt,
            "proceedsFromLinesOfCredit" => owner.Facts.UsGaap.ProceedsFromLinesOfCredit,
            "proceedsFromPaymentsForOtherFinancingActivities" => owner.Facts.UsGaap.ProceedsFromPaymentsForOtherFinancingActivities,
            "proceedsFromRentsReceived" => owner.Facts.UsGaap.ProceedsFromRentsReceived,
            "proceedsFromRepaymentsOfLinesOfCredit" => owner.Facts.UsGaap.ProceedsFromRepaymentsOfLinesOfCredit,
            "proceedsFromRepaymentsOfOtherLongTermDebt" => owner.Facts.UsGaap.ProceedsFromRepaymentsOfOtherLongTermDebt,
            "proceedsFromSaleAndMaturityOfMarketableSecurities" => owner.Facts.UsGaap.ProceedsFromSaleAndMaturityOfMarketableSecurities,
            "proceedsFromSaleOfIntangibleAssets" => owner.Facts.UsGaap.ProceedsFromSaleOfIntangibleAssets,
            "proceedsFromSaleOfProductiveAssets" => owner.Facts.UsGaap.ProceedsFromSaleOfProductiveAssets,
            "proceedsFromSaleOfPropertyHeldForSale" => owner.Facts.UsGaap.ProceedsFromSaleOfPropertyHeldForSale,
            "profitLoss" => owner.Facts.UsGaap.ProfitLoss,
            "propertyPlantAndEquipmentGross" => owner.Facts.UsGaap.PropertyPlantAndEquipmentGross,
            "propertyPlantAndEquipmentNet" => owner.Facts.UsGaap.PropertyPlantAndEquipmentNet,
            "propertyPlantAndEquipmentOther" => owner.Facts.UsGaap.PropertyPlantAndEquipmentOther,
            "provisionForDoubtfulAccounts" => owner.Facts.UsGaap.ProvisionForDoubtfulAccounts,
            "provisionForLoanLossesExpensed" => owner.Facts.UsGaap.ProvisionForLoanLossesExpensed,
            "purchaseCommitmentRemainingMinimumAmountCommitted" => owner.Facts.UsGaap.PurchaseCommitmentRemainingMinimumAmountCommitted,
            "purchaseObligationDueAfterFifthYear" => owner.Facts.UsGaap.PurchaseObligationDueAfterFifthYear,
            "purchaseObligationDueInFourthAndFifthYear" => owner.Facts.UsGaap.PurchaseObligationDueInFourthAndFifthYear,
            "purchaseObligationDueInNextTwelveMonths" => owner.Facts.UsGaap.PurchaseObligationDueInNextTwelveMonths,
            "purchaseObligationDueInSecondAndThirdYear" => owner.Facts.UsGaap.PurchaseObligationDueInSecondAndThirdYear,
            "reclassificationFromAccumulatedOtherComprehensiveIncomeCurrentPeriodNetOfTax" => owner.Facts.UsGaap.ReclassificationFromAccumulatedOtherComprehensiveIncomeCurrentPeriodNetOfTax,
            "reclassificationFromAociCurrentPeriodNetOfTaxAttributableToParent" => owner.Facts.UsGaap.ReclassificationFromAociCurrentPeriodNetOfTaxAttributableToParent,
            "repaymentsOfDebt" => owner.Facts.UsGaap.RepaymentsOfDebt,
            "repaymentsOfLinesOfCredit" => owner.Facts.UsGaap.RepaymentsOfLinesOfCredit,
            "repaymentsOfLongTermCapitalLeaseObligations" => owner.Facts.UsGaap.RepaymentsOfLongTermCapitalLeaseObligations,
            "repaymentsOfLongTermDebt" => owner.Facts.UsGaap.RepaymentsOfLongTermDebt,
            "repaymentsOfLongTermLinesOfCredit" => owner.Facts.UsGaap.RepaymentsOfLongTermLinesOfCredit,
            "restrictedCashAndInvestmentsCurrent" => owner.Facts.UsGaap.RestrictedCashAndInvestmentsCurrent,
            "restrictedCashAndInvestmentsNoncurrent" => owner.Facts.UsGaap.RestrictedCashAndInvestmentsNoncurrent,
            "restrictedCashCurrent" => owner.Facts.UsGaap.RestrictedCashCurrent,
            "restrictedCashNoncurrent" => owner.Facts.UsGaap.RestrictedCashNoncurrent,
            "restructuringCharges" => owner.Facts.UsGaap.RestructuringCharges,
            "retainedEarningsAccumulatedDeficit" => owner.Facts.UsGaap.RetainedEarningsAccumulatedDeficit,
            "revenueFromContractWithCustomerExcludingAssessedTax" => owner.Facts.UsGaap.RevenueFromContractWithCustomerExcludingAssessedTax,
            "revenueFromContractWithCustomerIncludingAssessedTax" => owner.Facts.UsGaap.RevenueFromContractWithCustomerIncludingAssessedTax,
            "revenueNotFromContractWithCustomer" => owner.Facts.UsGaap.RevenueNotFromContractWithCustomer,
            "revenueRemainingPerformanceObligation" => owner.Facts.UsGaap.RevenueRemainingPerformanceObligation,
            "revenueRemainingPerformanceObligationPercentage" => owner.Facts.UsGaap.RevenueRemainingPerformanceObligationPercentage,
            "revenues" => owner.Facts.UsGaap.Revenues,
            "rightOfUseAssetObtainedInExchangeForFinanceLeaseLiability" => owner.Facts.UsGaap.RightOfUseAssetObtainedInExchangeForFinanceLeaseLiability,
            "rightOfUseAssetObtainedInExchangeForOperatingLeaseLiability" => owner.Facts.UsGaap.RightOfUseAssetObtainedInExchangeForOperatingLeaseLiability,
            "saleLeasebackTransactionNetProceedsFinancingActivities" => owner.Facts.UsGaap.SaleLeasebackTransactionNetProceedsFinancingActivities,
            "saleLeasebackTransactionNetProceedsInvestingActivities" => owner.Facts.UsGaap.SaleLeasebackTransactionNetProceedsInvestingActivities,
            "saleLeasebackTransactionRentExpense" => owner.Facts.UsGaap.SaleLeasebackTransactionRentExpense,
            "saleOfStockPricePerShare" => owner.Facts.UsGaap.SaleOfStockPricePerShare,
            "segmentReportingInformationRevenue" => owner.Facts.UsGaap.SegmentReportingInformationRevenue,
            "sellingGeneralAndAdministrativeExpense" => owner.Facts.UsGaap.SellingGeneralAndAdministrativeExpense,
            "severanceCosts" => owner.Facts.UsGaap.SeveranceCosts,
            "severanceCosts1" => owner.Facts.UsGaap.SeveranceCosts1,
            "shareBasedCompensation" => owner.Facts.UsGaap.ShareBasedCompensation,
            "shareBasedCompensationArrangementByShareBasedPaymentAwardDiscountFromMarketPricePurchaseDate" => owner.Facts.UsGaap.ShareBasedCompensationArrangementByShareBasedPaymentAwardDiscountFromMarketPricePurchaseDate,
            "shareBasedCompensationArrangementByShareBasedPaymentAwardEquityInstrumentsOtherThanOptionsVestedInPeriodTotalFairValue" => owner.Facts.UsGaap.ShareBasedCompensationArrangementByShareBasedPaymentAwardEquityInstrumentsOtherThanOptionsVestedInPeriodTotalFairValue,
            "shareBasedCompensationArrangementByShareBasedPaymentAwardNumberOfSharesAvailableForGrant" => owner.Facts.UsGaap.ShareBasedCompensationArrangementByShareBasedPaymentAwardNumberOfSharesAvailableForGrant,
            "shareBasedCompensationArrangementByShareBasedPaymentAwardOptionsExercisableWeightedAverageExercisePrice" => owner.Facts.UsGaap.ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsExercisableWeightedAverageExercisePrice,
            "shareBasedCompensationArrangementByShareBasedPaymentAwardOptionsExercisesInPeriodTotalIntrinsicValue" => owner.Facts.UsGaap.ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsExercisesInPeriodTotalIntrinsicValue,
            "shareBasedCompensationArrangementByShareBasedPaymentAwardOptionsOutstandingNumber" => owner.Facts.UsGaap.ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsOutstandingNumber,
            "sharePrice" => owner.Facts.UsGaap.SharePrice,
            "significantChangeInUnrecognizedTaxBenefitsIsReasonablyPossibleAmountOfUnrecordedBenefit" => owner.Facts.UsGaap.SignificantChangeInUnrecognizedTaxBenefitsIsReasonablyPossibleAmountOfUnrecordedBenefit,
            "significantPurchaseCommitmentRemainingMinimumAmountCommitted" => owner.Facts.UsGaap.SignificantPurchaseCommitmentRemainingMinimumAmountCommitted,
            "stockholdersEquity" => owner.Facts.UsGaap.StockholdersEquity,
            "stockholdersEquityIncludingPortionAttributableToNoncontrollingInterest" => owner.Facts.UsGaap.StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest,
            "stockholdersEquityOther" => owner.Facts.UsGaap.StockholdersEquityOther,
            "stockIssuedDuringPeriodSharesAcquisitions" => owner.Facts.UsGaap.StockIssuedDuringPeriodSharesAcquisitions,
            "stockIssuedDuringPeriodSharesConversionOfConvertibleSecurities" => owner.Facts.UsGaap.StockIssuedDuringPeriodSharesConversionOfConvertibleSecurities,
            "stockIssuedDuringPeriodValueAcquisitions" => owner.Facts.UsGaap.StockIssuedDuringPeriodValueAcquisitions,
            "stockIssuedDuringPeriodValueConversionOfConvertibleSecurities" => owner.Facts.UsGaap.StockIssuedDuringPeriodValueConversionOfConvertibleSecurities,
            "stockRepurchasedAndRetiredDuringPeriodShares" => owner.Facts.UsGaap.StockRepurchasedAndRetiredDuringPeriodShares,
            "stockRepurchasedAndRetiredDuringPeriodValue" => owner.Facts.UsGaap.StockRepurchasedAndRetiredDuringPeriodValue,
            "stockRepurchasedDuringPeriodShares" => owner.Facts.UsGaap.StockRepurchasedDuringPeriodShares,
            "stockRepurchasedDuringPeriodValue" => owner.Facts.UsGaap.StockRepurchasedDuringPeriodValue,
            "stockRepurchaseProgramAuthorizedAmount" => owner.Facts.UsGaap.StockRepurchaseProgramAuthorizedAmount,
            "stockRepurchaseProgramRemainingAuthorizedRepurchaseAmount" => owner.Facts.UsGaap.StockRepurchaseProgramRemainingAuthorizedRepurchaseAmount,
            "subleaseIncome" => owner.Facts.UsGaap.SubleaseIncome,
            "taxEffectOfExtraordinaryItem" => owner.Facts.UsGaap.TaxEffectOfExtraordinaryItem,
            "taxesPayableCurrent" => owner.Facts.UsGaap.TaxesPayableCurrent,
            "treasuryStockAcquiredAverageCostPerShare" => owner.Facts.UsGaap.TreasuryStockAcquiredAverageCostPerShare,
            "treasuryStockShares" => owner.Facts.UsGaap.TreasuryStockShares,
            "treasuryStockValue" => owner.Facts.UsGaap.TreasuryStockValue,
            "unamortizedDebtIssuanceExpense" => owner.Facts.UsGaap.UnamortizedDebtIssuanceExpense,
            "unbilledReceivablesCurrent" => owner.Facts.UsGaap.UnbilledReceivablesCurrent,
            "undistributedEarningsAllocatedToParticipatingSecurities" => owner.Facts.UsGaap.UndistributedEarningsAllocatedToParticipatingSecurities,
            "undistributedEarningsLossAllocatedToParticipatingSecuritiesBasic" => owner.Facts.UsGaap.UndistributedEarningsLossAllocatedToParticipatingSecuritiesBasic,
            "unrecognizedTaxBenefits" => owner.Facts.UsGaap.UnrecognizedTaxBenefits,
            "unrecognizedTaxBenefitsDecreasesResultingFromCurrentPeriodTaxPositions" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsDecreasesResultingFromCurrentPeriodTaxPositions,
            "unrecognizedTaxBenefitsDecreasesResultingFromPriorPeriodTaxPositions" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsDecreasesResultingFromPriorPeriodTaxPositions,
            "unrecognizedTaxBenefitsDecreasesResultingFromSettlementsWithTaxingAuthorities" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsDecreasesResultingFromSettlementsWithTaxingAuthorities,
            "unrecognizedTaxBenefitsIncreasesResultingFromAcquisition" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsIncreasesResultingFromAcquisition,
            "unrecognizedTaxBenefitsIncreasesResultingFromCurrentPeriodTaxPositions" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsIncreasesResultingFromCurrentPeriodTaxPositions,
            "unrecognizedTaxBenefitsIncreasesResultingFromPriorPeriodTaxPositions" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsIncreasesResultingFromPriorPeriodTaxPositions,
            "unrecognizedTaxBenefitsInterestOnIncomeTaxesAccrued" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsInterestOnIncomeTaxesAccrued,
            "unrecognizedTaxBenefitsReductionsResultingFromLapseOfApplicableStatuteOfLimitations" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsReductionsResultingFromLapseOfApplicableStatuteOfLimitations,
            "unrecognizedTaxBenefitsThatWouldImpactEffectiveTaxRate" => owner.Facts.UsGaap.UnrecognizedTaxBenefitsThatWouldImpactEffectiveTaxRate,
            "valuationAllowanceDeferredTaxAssetChangeInAmount" => owner.Facts.UsGaap.ValuationAllowanceDeferredTaxAssetChangeInAmount,
            "valuationAllowancesAndReservesBalance" => owner.Facts.UsGaap.ValuationAllowancesAndReservesBalance,
            "weightedAverageNumberOfDilutedSharesOutstanding" => owner.Facts.UsGaap.WeightedAverageNumberOfDilutedSharesOutstanding,
            "weightedAverageNumberOfSharesIssuedBasic" => owner.Facts.UsGaap.WeightedAverageNumberOfSharesIssuedBasic,
            "weightedAverageNumberOfSharesOutstandingBasic" => owner.Facts.UsGaap.WeightedAverageNumberOfSharesOutstandingBasic,
            "weightedAverageNumberOfSharesRestrictedStock" => owner.Facts.UsGaap.WeightedAverageNumberOfSharesRestrictedStock,
            "decreaseInUnrecognizedTaxBenefitsIsReasonablyPossible" => owner.Facts.UsGaap.DecreaseInUnrecognizedTaxBenefitsIsReasonablyPossible,
            "disposalGroupIncludingDiscontinuedOperationOtherCurrentAssets" => owner.Facts.UsGaap.DisposalGroupIncludingDiscontinuedOperationOtherCurrentAssets,
            "disposalGroupIncludingDiscontinuedOperationPropertyPlantAndEquipment" => owner.Facts.UsGaap.DisposalGroupIncludingDiscontinuedOperationPropertyPlantAndEquipment,
            "equitySecuritiesWithoutReadilyDeterminableFairValueAmount" => owner.Facts.UsGaap.EquitySecuritiesWithoutReadilyDeterminableFairValueAmount,
            "distributionMadeToLimitedPartnerUnitDistribution" => owner.Facts.UsGaap.DistributionMadeToLimitedPartnerUnitDistribution,
            "equitySecuritiesFvNiUnrealizedLoss" => owner.Facts.UsGaap.EquitySecuritiesFvNiUnrealizedLoss,
            "gainLossOnInvestments" => owner.Facts.UsGaap.GainLossOnInvestments,
            "otherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationReclassificationAdjustmentFromAOCIRealizedUponSaleOrLiquidationNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationReclassificationAdjustmentFromAOCIRealizedUponSaleOrLiquidationNetOfTax,
            "otherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationReclassificationAdjustmentFromAOCIRealizedUponSaleOrLiquidationTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationReclassificationAdjustmentFromAOCIRealizedUponSaleOrLiquidationTax,
            "unrealizedGainLossOnInvestments" => owner.Facts.UsGaap.UnrealizedGainLossOnInvestments,
            "accruedIncomeTaxes" => owner.Facts.UsGaap.AccruedIncomeTaxes,
            "effectiveIncomeTaxRateReconciliationDispositionOfBusiness" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationDispositionOfBusiness,
            "effectiveIncomeTaxRateReconciliationGiltiAmount" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationGiltiAmount,
            "effectiveIncomeTaxRateReconciliationNondeductibleExpenseShareBasedCompensationCost" => owner.Facts.UsGaap.EffectiveIncomeTaxRateReconciliationNondeductibleExpenseShareBasedCompensationCost,
            "governmentAssistanceAmount" => owner.Facts.UsGaap.GovernmentAssistanceAmount,
            "otherComprehensiveIncomeForeignCurrencyTransactionAndTranslationGainLossArisingDuringPeriodNetOfTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeForeignCurrencyTransactionAndTranslationGainLossArisingDuringPeriodNetOfTax,
            "otherComprehensiveIncomeForeignCurrencyTranslationGainLossArisingDuringPeriodTax" => owner.Facts.UsGaap.OtherComprehensiveIncomeForeignCurrencyTranslationGainLossArisingDuringPeriodTax,
            "deferredRevenueCurrent" => owner.Facts.UsGaap.DeferredRevenueCurrent,
            "extinguishmentOfDebtGainLossNetOfTax" => owner.Facts.UsGaap.ExtinguishmentOfDebtGainLossNetOfTax,
            "notesIssued1" => owner.Facts.UsGaap.NotesIssued1,
            "noncashContributionExpense" => owner.Facts.UsGaap.NoncashContributionExpense,
            "debtInstrumentFaceAmount" => owner.Facts.UsGaap.DebtInstrumentFaceAmount,
            "debtInstrumentIncreaseDecreaseForPeriodNet" => owner.Facts.UsGaap.DebtInstrumentIncreaseDecreaseForPeriodNet,
            "longtermDebtWeightedAverageInterestRate" => owner.Facts.UsGaap.LongtermDebtWeightedAverageInterestRate,
            "equityMethodInvestmentRealizedGainLossOnDisposal" => owner.Facts.UsGaap.EquityMethodInvestmentRealizedGainLossOnDisposal,
            "interestExpenseNonoperating" => owner.Facts.UsGaap.InterestExpenseNonoperating,
            "paymentsForProceedsFromBusinessesAndInterestInAffiliates" => owner.Facts.UsGaap.PaymentsForProceedsFromBusinessesAndInterestInAffiliates,
            "contractWithCustomerReceivableAfterAllowanceForCreditLoss" => owner.Facts.UsGaap.ContractWithCustomerReceivableAfterAllowanceForCreditLoss,
            "definedBenefitPlanContributionsByEmployer" => owner.Facts.UsGaap.DefinedBenefitPlanContributionsByEmployer,
            "extinguishmentOfDebtAmount" => owner.Facts.UsGaap.ExtinguishmentOfDebtAmount,
            "increaseDecreaseInDeferredRevenue" => owner.Facts.UsGaap.IncreaseDecreaseInDeferredRevenue,
            _ => null,
        };
    }
}
